### ISSUE TITLE
Release on maven central

### ISSUE THREAD

**Issue by invadersmustdie** [soundcloud/prometheus-hystrix#2]
Couldn't find any version of this project on maven central. Any chance to release the current version soon?

**Comment by dennisosimon** [comment]
+1

**Comment by ahus1** [comment]
Instead of releasing this to maven central, what about migrating it to a submodule of the existing Prometheus simple client? They are both Apache 2 License...

**Comment by ahus1** [comment]
I see that there has been a discussion not to have this as a sub-module of the Prometheus simple client, see: https://github.com/prometheus/client_java/pull/15

But how can we proceed to keep this project active, and also provide a maven central version? Any thoughts from the maintainers?

**Comment by charithe** [comment]
I agree that it would be really helpful to have a Maven Central release. In the mean time, you could use Jitpack to obtain the latest release artifacts. (https://jitpack.io/#soundcloud/prometheus-hystrix/3.1.0)

**Comment by erikbo** [comment]
Is there any current plans on releasing this to maven central? Would be really helpful for us.

**Comment by beorn7** [comment]
This project is essentially orphaned. Ideally, somebody would show up to take over the maintainer role and fork this outside of the SoundCloud GitHub org. Then that person could go forward with Maven etc.

**Comment by ahus1** [comment]
I'm volunteering as a new maintainer. Like @beorn7 suggested I forked the repository: [ahus1/prometheus-hystrix](https://github.com/ahus1/prometheus-hystrix).

The Release 3.1.0 is now available on Maven Central: http://repo1.maven.org/maven2/de/ahus1/prometheus/hystrix/prometheus-hystrix/

I've pushed a pull request #6 to update the central README.

**Comment by beorn7** [comment]
Thank you very much. I'll close this issue, but file a new one to graveyard this repo after a grace period.
